### ISSUE TITLE
[Bug] /color link and /color unlink don't work

### ISSUE THREAD

**Issue by Soapy7261** [greys-bots/sheep#19]
When trying to use the /color link command the bot throws an error
Error:
Cannot read property 'role_mode' of undefined
![Screenshot 2022-12-02 185604](https://user-images.githubusercontent.com/81933267/205410704-5c31b9e2-b21e-47a9-8bb5-016e0df9bd6a.png)

**Comment by Soapy7261** [comment]
Same with /color unlink

**Comment by selenated** [comment]
thanks for the report! we'll try to check it out here in a bit :)

**Comment by selenated** [comment]
sorry it took so long, having a job has made things like this harder to get to ^^;

just pushed some changes that should hopefully fix this if it wasn't fixed already, hopefully it works better now! gonna go ahead and close this for the time being, feel free to reopen if the issue crops up again

**Comment by Soapy7261** [comment]
👍
