### ISSUE TITLE
Change how permissions are handled

### ISSUE THREAD

**Issue by cs-deathmatch** [greys-bots/sheep#23]
Currently, when a color role is created it copies the permissions from @ everyone. this seems fine, but has immediate issues if you want to change the @ everyone permissions.

There's no reason to even grant any permissions to the color role, you can make an empty role that has no permissions.

**Comment by ranidspace** [comment]
adding `permissions: 0` to the `var options` of roles should work. and i agree it makes it a lot harder to change permissions for the @everyone role

**Comment by selenated** [comment]
I think at the time this behavior might've been a request from someone, but I agree that it's more of a pain than anything else for most users 😅

Shouldn't be hard to update, will take a look at this here soon!

**Comment by selenated** [comment]
Oh geez, I forgot to update this, sorry! This behavior is now implemented, and there's now also a `/admin permfix` command that'll remove permissions on any existing (user-based) color role. Thanks for the feedback!
