### ISSUE TITLE
postgresql

### ISSUE THREAD

**Issue by MuskyKanne** [greys-bots/sheep#3]
Hello, you could make the templates of the .sqlite files available?

**Comment by selenated** [comment]
I'm not sure what you mean. The bot should create all the necessary tables without you having to do anything

**Comment by MuskyKanne** [comment]
Error: connect ECONNREFUSED 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432

The bot is giving this error, I wanted the file that I can add to my base date information,

**Comment by selenated** [comment]
You need to make sure you've got postgres set up and running, and add the right variables to your .env file

Check [this](https://node-postgres.com/features/connecting) for the variables you'll need to connect
